### ISSUE TITLE
Sorting List by Countrys

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#15]
## Value Proposition

**As a User** 

**I want to**  see the list of surfspots first sorted by countrys.

**to be able**  to just get the spots which are in my selected country.

## Description
<img width="505" alt="Bildschirmfoto 2022-12-16 um 09 39 04" src="https://user-images.githubusercontent.com/115305668/208069435-69754bdb-94cf-4f33-802a-7cbb0c12aa48.png">

## Acceptance Criteria

- [ ] When clicking the menu button, there should first be a list of countrys rendered in which surfspots are.
- [ ] when clicking on a country, the surfspots within this country should be rendered as a list.
- [ ] the user should be able to click in the whole area between the title and the arrow symbol.
- [ ] both lists should be with a routing.
- [ ] on the rendered spots site should be a back button to go back to the country list

## Tasks

(for developers team)

- [ ] branch feature/ListSortedbyCountrys.
- [ ] new site folder for countrys and spots.
- [ ] map over the surfspots for countrys and setting the countrys in a state, if they still are in the state then not.
- [ ] when clicking on the menu button rendering the countrys site. When clicking on a country, then mapping over the surfspots array for all spots in the land. 
- [ ] on the surfspot side, creating a back button, to go back to the country list site.
- [ ] testing.

**Comment by AntjeWalter** [comment]
Looks good to me :)
