### ISSUE TITLE
SpotDetailsSocial

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#16]
## Value Proposition

**As a User** 

**I want to**  see a page where comments from user can be placed.

**to be able**  to comment and read comments about the spot.

## Description
<img width="299" alt="Bildschirmfoto 2022-12-16 um 11 07 18" src="https://user-images.githubusercontent.com/115305668/208085464-7a6b10f2-067e-4f8f-a2ad-65b627ec90e8.png">

## Acceptance Criteria

- [ ] There has to be a social button.
- [ ] When onclick the social button, the spot information should be gone and the social component should be rendered.
- [ ] The social component includes a footer, which has an input field and a send button. 
- [ ] And a comments section where the comments about the spot will be shown

## Tasks

(for developers team)

- [ ] branch feature/spotdetailsSocial.
- [ ] Creating social button
- [ ] onclick on social and infos button to change between these two components with a boolean state.
- [ ] creating footer for social site, including an input field and a submit button.
- [ ] creating the a list and the list items
- [ ] styling with styled components
- [ ] testing.

**Comment by NeeleWaehnke** [comment]
Sieht gut aus! Ich würde evtl. noch festlegen an welcher Stelle neue Kommentare angezeigt werden sollen, also oben oder unten in der Liste, aber das ist nur eine Kleinigkeit :)
