### ISSUE TITLE
Users map position saved in state

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#19]
## Value Proposition

**As a User** 

**I want to**  get to the map position which i head before i went on a spotdetail page.

**to be able**  to not move again over the map to the last position.

## Description
Normally the map position is at the same point when opening the map component. So the user has to navigate after every rerender to the wished position. With a state which saves the center of the map at every change the map should be the same after a rerender.

## Acceptance Criteria

- [ ] When starting the app, the position on the map is always the same. 
- [ ] After using another component on the app, like a spotdetail site or a list, the user has to see the last viewed position on the map.

## Tasks

(for developers team)

- [ ] branch feature/mappositionState.
- [ ] new state in map component.
- [ ] state safes the centered position when user is going to another component.
- [ ] testing.
