### ISSUE TITLE
My Location

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#20]
## Value Proposition

**As a User** 

**I want to**  get the map position on my current location.

**to be able**  to see surfspots near to my location.

## Description
When clicking the location button, the map position should switch to the location where the user currently is.

## Acceptance Criteria

- [ ] There has to be a position button.
- [ ] When clicking on the position button, the map position change to the users real position

## Tasks

(for developers team)

- [ ] branch feature/positionButton
- [ ] creating position button
- [ ] when clicking the position button, the map position changes to the users position.
- [ ] testing.
