### ISSUE TITLE
Windforecast on spotdetailpage

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#21]
## Value Proposition

**As a User** 

**I want to**  see the windforecast for the spot on which spotdetail page i am.

**to be able**  to know if the wind is good for surfing the next days.

## Description

<img width="247" alt="Bildschirmfoto 2022-12-18 um 23 17 02" src="https://user-images.githubusercontent.com/115305668/208324667-245aa8a8-6a15-4fe8-8d60-aac9f7363902.png">

## Acceptance Criteria

- [ ] There has to be a windforecast on the spotdetail page for the selected spot.

## Tasks

(for developers team)

- [ ] branch feature/windforecast
- [ ] fetching the windforecast on the spotdetail page. 
- [ ] the fetch should be change for every spot, so the forecast is for the choosen spot
- [ ] testing.

**Comment by NeeleWaehnke** [comment]
sieht gut aus!
