### ISSUE TITLE
Add Spot

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#22]
## Value Proposition

**As a User** 

**I want to**  add a new surfspot to the map

**to be able**  to share my experience with other users.

## Description

<img width="257" alt="Bildschirmfoto 2022-12-18 um 23 29 31" src="https://user-images.githubusercontent.com/115305668/208325298-551a2eb2-1a1b-4f92-a064-c722fd6fa993.png">

## Acceptance Criteria

- [ ] There has to be a add button on the map.
- [ ] After clicking the add button, there has to be a form to fill in the information about the spot.
- [ ] After Submitting the form, a new marker should be shown on the map. 

## Tasks

(for developers team)

- [ ] branch feature/addSpot
- [ ] new button on the map component to add a spot.
- [ ] there should be a form to get the information about the new spot
- [ ] the information about the new spot should be saved in the surfspots array
- [ ] the new spot should be rendered in the list and on the map
- [ ] testing.

**Comment by ufelgen** [comment]
Hallo Jan, magst du vielleicht noch spezifizieren, wie das Formular aussehen soll bzw. welche Daten erfasst werden, die dann wo wie gerendert werden (vorher/nachher)? ansonsten prima :)
