### ISSUE TITLE
DB Connection

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#23]
## Value Proposition

**As a developer** 

**I want to**  save the data in a databse

**to be able**  to store it and let users add spots later.

## Description

I am using a MongoDB to replace my surfspots array.

## Acceptance Criteria

Only Tasks for me

## Tasks

(for developers team)

- [ ] branch feature/dbConnect
- [ ] setup a new DB on mongoDB.com
- [ ] add a db folder to my project including the data model and a dbConnect.js
- [ ] write a local .env.local file - that will be added to the .gitignore
- [ ] write a dbconnect and a model
- [ ] write a api connection
- [ ] write a fetchhook
- [ ] replace all the refers in the code from the old "data.js" file to the new database
- [ ] testing.

**Comment by ufelgen** [comment]
hab nichts auszusetzen! ein acceptance criterium für mich wäre "works as before" ;) aber davon sollte ja ausgegangen werden. Viel Erfolg!
