### ISSUE TITLE
Search Spots around a place 

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#26]
## Value Proposition

**As a User** 

**I want to**  search for Surfspots around a place.

**to be able**  to know which surfspots are near to this location.

## Description

<img width="259" alt="Bildschirmfoto 2022-12-26 um 15 37 28" src="https://user-images.githubusercontent.com/115305668/209559551-aa5475f3-40e0-4b63-8e2b-4f2cc68fc8ea.png">

## Acceptance Criteria

- [ ] The header has a button to search for a specific location.
- [ ] When the button is clicked, the user should be able to type in a place.
- [ ] The Map changes the position to the searched place and shows the spot around the place

## Tasks

(for developers team)

- [ ] branch feature/searcharoundplace.
- [ ] create new button in the header.
- [ ] install the plugin for the search for react leaflet.
- [ ] connecting the component with the button and the map
- [ ] testing.

**Comment by ufelgen** [comment]
Hi Jan, gute US! vielleicht (aber kein Muss) spezifizierst du noch, was in das Suchfeld eingegeben werden kann, also Koordinaten oder ein Ort/Stadt oder beides?
