### ISSUE TITLE
Favorite spot

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#31]
## Value Proposition

**As a User** 

**I want to**  mark some spots am my favorite spots.

**to be able**  to see a list of my favorite spots and get faster to their detail page.

## Description

<img width="260" alt="Bildschirmfoto 2023-01-04 um 19 08 10" src="https://user-images.githubusercontent.com/115305668/210630870-310367ae-e307-4d38-a363-08d67a88b6fd.png">

## Acceptance Criteria

- [ ] There has to be a button to select a spot as a favorite or delete them as a favorite.
- [ ] There has to be a list with all as a favorite marked spots

## Tasks

(for developers team)

- [ ] branch feature/favoriteSpot
- [ ] creating a button on the spot detail page.
- [ ] id of the favorite spots will be saved in a localhost memory.
- [ ] rendering a list of the spots which are matching the id of favorite spot.
- [ ] testing.

**Comment by ufelgen** [comment]
ich würde mir hier ein Scribble oder Design wünschen - ist aber kein Muss. Allerdings würde ich noch spezifizieren, wie das Routing zur Favourite Page funktioniert. also hast du nen Icon im Header oder irgendwo anders? oder wo werden die fav spots angezeigt?

**Comment by JanRaadts** [comment]
did it :)
