### ISSUE TITLE
Picture Upload on Add Spot Page

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#36]
## Value Proposition

**As a User** 

**I want to**  load up a picture while adding a new spot.

**to be able**  to show other users how the spot looks like.

## Description

On the add Spot form there will be a upload button to upload a picture

## Acceptance Criteria

- [ ] There has to be a button to upload a picture

## Tasks

(for developers team)

- [ ] branch feature/picture upload
- [ ] using cloudinary for the picture upload.
- [ ] testing.

**Comment by JanRaadts** [comment]
Gracias :D
