### ISSUE TITLE
Marker for every SurfSpot

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#5]
## Value Proposition

**As a User** 

**I want to see a marker on the map at a point where a Surfspot is.** 

**to be able to know where a Surfspot is** 

## Description
<img width="233" alt="Bildschirmfoto 2022-12-09 um 13 42 40" src="https://user-images.githubusercontent.com/115305668/206715533-48b706e5-8d08-4cf2-8f87-d1b866a0b4c5.png">

## Acceptance Criteria

- [x] there has to be a marker on the map on each point where a Surfspot is

## Tasks

(for developers team)

- [x] branch feature/markerOnTheMap
- [x] mapping over the SurfSpot array and returning for every Surfspot a marker on the map using the coordinates
- [x] testing
