### ISSUE TITLE
Full screen map with leaflet

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#6]
## Value Proposition

**As a User** 

**I want to see a map when i start the app.** 

**to be able to slide around in the map to get to different locations** 

## Description
<img width="303" alt="Bildschirmfoto 2022-12-09 um 13 15 07" src="https://user-images.githubusercontent.com/115305668/206710699-ca89c4d3-ad6a-49b6-9916-b94def1d5663.png">

## Acceptance Criteria

- [ ] the map has to be on the full width and height of the viewfield
- [ ] You have to be able to zoom in and out on the map.
- [ ] You have to be able to maneuver on the map by swiping your finger over the app

## Tasks

(for developers team)

- [ ] branch feature/mapConnect
- [ ] fetch and install the leaflet map api
- [ ] style the map to full width and height
- [ ] testing
