### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by JanRaadts** [JanRaadts/capstone-project#7]
## Value Proposition

**As a User** 

**I want to see a Header with a button** 

**to change from the map view to my List** 

## Description

<img width="220" alt="Bildschirmfoto 2022-12-12 um 10 01 23" src="https://user-images.githubusercontent.com/115305668/207069449-29127ae6-343a-4584-926b-c31565fca149.png">

## Acceptance Criteria

- [ ] Header with a List Symbol button

## Tasks

(for developers team)

- [ ] create branch feature/Header
- [ ] create component header
- [ ] header returns an at the top fixed section with a button
- [ ] Onclick on the button to switch to the list section 
- [ ] When Onclick on the list section the user gets the full screen map again
- [ ] testing

**Comment by andy-schwedler** [comment]
> testing

What do you mean by testing? user acceptance test?

**Comment by JanRaadts** [comment]
@andy-schwedler Just clicking around looking for some bugs.. :)
